parameters:
   elk.endpoint: '%env(ELK_ENDPOINT)%'

imports:
    - 'services/shared_services.yaml'
    - 'services/products_services.yaml'
    - 'services/users_services.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/*/Domain/Entity/' 
            - '../src/Shared/Infrastructure/Kernel.php'

    # Commands
    App\Shared\Application\Bus\Command\CommandBus:
        public: true
        calls:
            - method: registerHandler
              arguments:
                - App\Products\Application\Commands\Create\CreateProduct
                - ['@App\Products\Application\Commands\Create\CreateProductHandler', 'handle']
            - method: registerHandler
              arguments:
                - App\Products\Application\Commands\Delete\DeleteProduct
                - ['@App\Products\Application\Commands\Delete\DeleteProductHandler', 'handle'] 
            - method: registerHandler
              arguments:
                - App\Products\Application\Commands\Update\UpdateProduct
                - ['@App\Products\Application\Commands\Update\UpdateProductHandler', 'handle'] 
            - method: registerHandler
              arguments:
                - App\Users\Application\Commands\Create\CreateUser
                - ['@App\Users\Application\Commands\Create\CreateUserHandler', 'handle'] 
            - method: registerHandler
              arguments:
                - App\Users\Application\Commands\ChangePassword\ChangeUserPassword
                - ['@App\Users\Application\Commands\ChangePassword\ChangeUserPasswordHandler', 'handle'] 

    # Queries
    App\Shared\Application\Bus\Query\QueryBus:
        public: true
        calls:
            - method: 'registerHandler'
              arguments:
                  - 'App\Products\Application\Queries\GetAll\GetAllProducts'
                  - ['@App\Products\Application\Queries\GetAll\GetAllProductsHandler', 'handle']  
            - method: 'registerHandler'
              arguments:
                  - 'App\Products\Application\Queries\GetById\GetProductById'
                  - ['@App\Products\Application\Queries\GetById\GetProductByIdHandler', 'handle']  
            - method: 'registerHandler'
              arguments:
              - 'App\Users\Application\Queries\GetUser\GetUserQuery'
              - ['@App\Users\Application\Queries\GetUser\GetUserHandler', 'handle'] 

    





